
import { GoogleGenAI, Modality } from "@google/genai";

const getAiClient = () => {
    // The API key is expected to be set in the environment variables.
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable not set.");
    }
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

/**
 * Generates an image using the Imagen model based on a text prompt.
 * @param prompt The text prompt describing the image to generate.
 * @returns A promise that resolves to the base64-encoded image data URL.
 */
export const generateImageWithImagen = async (prompt: string): Promise<string> => {
    const ai = getAiClient();
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: '16:9', // Optimized for banners
        },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
        throw new Error("The model did not return any images.");
    }

    const base64ImageBytes = response.generatedImages[0].image.imageBytes;
    return `data:image/jpeg;base64,${base64ImageBytes}`;
};

/**
 * Edits an existing image using the Gemini 2.5 Flash Image model based on a text prompt.
 * @param base64Image The base64-encoded string of the image to edit.
 * @param prompt The text prompt describing the desired edits.
 * @returns A promise that resolves to the base64-encoded data URL of the edited image.
 */
export const editImageWithNanoBanana = async (
    base64Image: string,
    prompt: string
): Promise<string> => {
    const ai = getAiClient();
    
    const match = base64Image.match(/^data:(image\/\w+);base64,(.*)$/);
    if (!match) {
        throw new Error("Invalid base64 image string format.");
    }
    const [, mimeType, data] = match;

    const imagePart = {
        inlineData: {
            data,
            mimeType,
        },
    };

    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [imagePart, textPart],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    if (!response.candidates || response.candidates.length === 0) {
        throw new Error("Model response is empty or invalid.");
    }

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const newBase64Data = part.inlineData.data;
            const newMimeType = part.inlineData.mimeType;
            return `data:${newMimeType};base64,${newBase64Data}`;
        }
    }

    throw new Error("No image was generated by the model.");
};
